_BASE_: ../base_config.yaml


MODEL:
  META_ARCHITECTURE: "PARQ_Deformable"
  CONV_MODEL:
    NORM: "BN"
    HEAD_NORM: "BN"
    ACT: "ReLU"
    N_FILTERS: [64, 96, 128, 256]
    FIRST_STRIDE: (2, 2, 2)

  PARQ_MODEL:
    NUM_QUERIES: 8
    PARQ_LOSS:
      DO_CLF_FOCAL: False

  DEFORMABLE:
    N_HEADS: 16
    N_LEVELS: 4
    N_ENC_LAYERS: 2
    N_DEC_LAYERS: 2
    FFN_DIM: 512
    DROPOUT: 0.1
    ACTIVATION: "RELU"
    N_ENC_POINTS: 4
    N_DEC_POINTS: 32
    DECODER_ONLY: False

DATA:
  PATCH_SIZE: [64, 64, 64]
  OVERLAP: [32, 32, 32]

SOLVER:
  LR_SCHEDULER_NAME: "CosineAnnealingLR"
  OPTIMIZER: "ADAMW_8BIT"
  AMP:
    ENABLED: True
  SCHED_CYCLE: 68000
  BASE_LR: 0.0001
  MIN_LR: 0.000005
  MAX_ITER: 68000
  FLAT_ITER: 68000
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 5.0

  SCANS_PER_BATCH: 1
  SAMPLES_PER_SCAN: 8
  GRAD_ACCUM:
    STEPS: 1
    ENABLED: False
TEST:
  PATCHES_PER_ITER: 8
