_BASE_: ../deform/deform_base_crop_vessel.yaml
SEED: 2000

MODEL:
  NAME: "aug_cnn_4l_short_input_edt_fp_aneu_done_nov_z"
  META_ARCHITECTURE: "PARQ_Deformable_R"
  USE_VESSEL_INFO: "start" # "start", "pos_emb", "no"
  USE_CVS_INFO: "no"
  DEFORMABLE:
    DECODER_ONLY: True
    WITH_RECURRENCE: False
    SHARED_CENTER_HEAD: True
    USE_GLOBAL_PE: True
    USE_DEFORM_ATTN: True
    N_LEVELS: 4
SOLVER:
  SCANS_PER_BATCH: 16
  SAMPLES_PER_SCAN: 16
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 5.0
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
  SCHED_CYCLE: 18000
  BASE_LR: 0.0001
  MIN_LR: 0.00001
  MAX_ITER: 18000
  FLAT_ITER: 18000
  CHECKPOINT_PERIOD: 1000
TEST:
  PATCHES_PER_ITER: 16 #  24 = ~12GB
  NMS_TOPK: 40
DATALOADER:
  NUM_WORKERS: 16
DATA:
  PATCH_SIZE: [64, 64, 64]
  OVERLAP: [32, 32, 32]
  NORM_TYPE: "zscore"

  N_CHANNELS: 2 # TODO: automate this parameter so it doesn't require changing when using channels for vessel info
  CROPPING_AUG:
    ROTATION: [90.0, 90.0, 90.0]
    SPACING: [0.9, 1.8]
    PADDED_REORIENT: True
    TRANSFORM_RAD: False
  DIR:
    TRAIN:
      SCAN_DIR: "internal_train/crop_0.4"
      VESSEL_DIR: "internal_train/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_train/vein_mask_edt_comp"
      ANNOTATION_FILE: "./labels/gt/internal_train_crop_0.4_fps_done_extra_aneu.csv"

    VAL:
      SCAN_DIR: "internal_test/crop_0.4"
      ANNOTATION_FILE: "./labels/gt/internal_test_crop_0.4.csv"
      VESSEL_DIR: "internal_test/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_test/cvs_mask_edt_comp"
