"""
Tests for TRANSFORM_RAD parameter in RandomTranspose.

For each test case we:
  1. Build a 3D label volume with non-isotropic ellipsoids.
  2. Extract ground-truth ctr and rad from the label volume itself
     (so discretisation effects are already baked in).
  3. Run RandomTranspose with p=1.0 (guaranteed to fire).
  4. Re-extract ctr and rad from the *transposed* label volume.
  5. Check whether the transform's output rad matches the re-extracted
     rad.

This is done for both transform_rad=True and transform_rad=False so we
can observe which setting produces rad values consistent with the actual
transposed geometry.

~55 subcases are generated by varying:
  - volume shape
  - number / placement / radii of objects
  - which transpose axes fire (xy, zx, zy, combinations)
"""

import random
import itertools
import numpy as np
import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_ellipsoid_mask(shape, center, radii):
    """Boolean mask for an axis-aligned ellipsoid in a (D, H, W) volume."""
    grids = np.ogrid[:shape[0], :shape[1], :shape[2]]
    dist = sum(
        ((g - c) / max(r, 0.5)) ** 2
        for g, c, r in zip(grids, center, radii)
    )
    return dist <= 1.0


def extract_geometry_from_label(label_3d, obj_ids):
    """Re-extract half-extent radii and centres from a label volume.

    Returns (radii, centres) each of shape (N, 3) in (d, h, w) order.
    """
    radii, centres = [], []
    for oid in obj_ids:
        coords = np.argwhere(label_3d == oid)
        lo = coords.min(axis=0).astype(np.float64)
        hi = coords.max(axis=0).astype(np.float64)
        centres.append((lo + hi) / 2.0)
        radii.append((hi - lo) / 2.0)
    return np.array(radii), np.array(centres)


def build_sample(objects, vol_shape):
    """Build a sample dict with image, label, ctr, rad.

    vol_shape: (C, D, H, W).
    objects: list of dicts with 'center' (d,h,w) and 'radii' (rd,rh,rw).

    The ctr and rad arrays are extracted from the rasterised label volume
    so that they reflect exact voxel extents (no discretisation mismatch).

    Returns (sample_dict, list_of_object_ids).
    """
    _, d, h, w = vol_shape
    rng = np.random.RandomState(42)
    image = rng.randn(*vol_shape).astype(np.float32)
    label = np.zeros((1, d, h, w), dtype=np.float32)

    obj_ids = []
    for idx, obj in enumerate(objects, start=1):
        mask = make_ellipsoid_mask(
            (d, h, w), obj["center"], obj["radii"],
        )
        label[0][mask] = idx
        obj_ids.append(idx)

    # Extract ctr/rad from the actual voxelised label
    rads, ctrs = extract_geometry_from_label(label[0], obj_ids)

    sample = {
        "image": image,
        "label": label,
        "ctr": ctrs,
        "rad": rads,
    }
    return sample, obj_ids


def import_random_transpose():
    """Import RandomTranspose from the current project."""
    import sys
    import importlib
    project = "/projects/vig/alberto/medical/exploration/deform"
    sys.path.insert(0, project)
    try:
        mods_to_clear = [
            "src.transform.rotate",
            "src.transform.abstract_transform",
            "src.transform.image_process",
            "src.transform",
            "src",
        ]
        for mod in mods_to_clear:
            if mod in sys.modules:
                del sys.modules[mod]
        rotate_mod = importlib.import_module("src.transform.rotate")
        return rotate_mod.RandomTranspose
    finally:
        sys.path.remove(project)


# ---------------------------------------------------------------------------
# Case generation
# ---------------------------------------------------------------------------

VOLUME_SHAPES = [
    (1, 60, 80, 100),
    (1, 50, 50, 90),
    (1, 80, 120, 60),
    (1, 40, 70, 110),
    (1, 100, 60, 80),
]

OBJECT_SETS = [
    # Set A: 3 clearly non-isotropic objects
    [
        {"center": (25, 35, 45), "radii": (4, 10, 16)},
        {"center": (15, 20, 70), "radii": (8, 3, 12)},
        {"center": (35, 50, 25), "radii": (3, 14, 6)},
    ],
    # Set B: 2 objects, very elongated
    [
        {"center": (20, 30, 40), "radii": (3, 3, 15)},
        {"center": (30, 40, 60), "radii": (12, 4, 4)},
    ],
    # Set C: 4 objects, mixed
    [
        {"center": (20, 25, 30), "radii": (5, 8, 12)},
        {"center": (10, 50, 70), "radii": (7, 3, 10)},
        {"center": (30, 15, 50), "radii": (4, 11, 6)},
        {"center": (25, 40, 20), "radii": (9, 5, 3)},
    ],
    # Set D: 1 very anisotropic object
    [
        {"center": (20, 30, 40), "radii": (3, 12, 7)},
    ],
    # Set E: 2 objects with large aspect ratios
    [
        {"center": (20, 25, 45), "radii": (15, 4, 8)},
        {"center": (30, 55, 30), "radii": (5, 14, 3)},
    ],
]

# Which transpose axes to enable (only combos that actually transpose)
TRANSPOSE_COMBOS = [
    {"xy"},
    {"zx"},
    {"zy"},
    {"xy", "zx"},
    {"xy", "zy"},
    {"zx", "zy"},
    {"xy", "zx", "zy"},
]


def _clamp_objects_to_volume(objects, vol_shape):
    """Adjust object centres so ellipsoids fit inside the volume."""
    _, d, h, w = vol_shape
    clamped = []
    for obj in objects:
        c = list(obj["center"])
        r = list(obj["radii"])
        c[0] = min(max(c[0], r[0] + 1), d - r[0] - 2)
        c[1] = min(max(c[1], r[1] + 1), h - r[1] - 2)
        c[2] = min(max(c[2], r[2] + 1), w - r[2] - 2)
        clamped.append({"center": tuple(c), "radii": tuple(r)})
    return clamped


def generate_cases():
    """Generate ~55 (vol_shape, objects, transpose_combo) triples."""
    cases = []
    for vol_shape, obj_set, combo in itertools.product(
        VOLUME_SHAPES, OBJECT_SETS, TRANSPOSE_COMBOS,
    ):
        objs = _clamp_objects_to_volume(obj_set, vol_shape)
        combo_tag = '_'.join(sorted(combo))
        dims_tag = 'x'.join(str(s) for s in vol_shape[1:])
        case_id = (
            f"vol{dims_tag}"
            f"_obj{len(objs)}"
            f"_{combo_tag}"
        )
        cases.append(
            pytest.param(vol_shape, objs, combo, id=case_id),
        )
        if len(cases) >= 55:
            break
    return cases


CASES = generate_cases()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "vol_shape, objects, combo", CASES,
)
@pytest.mark.parametrize(
    "transform_rad", [True, False], ids=["rad_True", "rad_False"],
)
def test_transform_rad_consistency(
    vol_shape, objects, combo, transform_rad,
):
    """Check whether output rad matches re-extracted rad after transpose.

    The test builds a volume, runs RandomTranspose, then re-extracts
    radii from the transposed label.  It asserts that the output rad
    equals the re-extracted rad (within tolerance).

    This is run for both transform_rad=True and transform_rad=False
    so we can see which setting produces geometrically correct results.
    """
    RandomTranspose = import_random_transpose()

    sample, obj_ids = build_sample(objects, vol_shape)
    sample_copy = {k: v.copy() for k, v in sample.items()}

    # Only enable the axes in `combo`; p=1.0 guarantees they fire.
    transform = RandomTranspose(
        trans_xy=("xy" in combo),
        trans_zx=("zx" in combo),
        trans_zy=("zy" in combo),
        p=1.0,
        transform_rad=transform_rad,
    )

    # Seed doesn't matter with p=1.0 but set for reproducibility.
    random.seed(0)
    result = transform(sample_copy)

    # Re-extract ground-truth geometry from the transposed label.
    extracted_rad, extracted_ctr = extract_geometry_from_label(
        result["label"][0], obj_ids,
    )

    np.testing.assert_allclose(
        result["ctr"], extracted_ctr, atol=1.0,
        err_msg=(
            f"ctr mismatch "
            f"(transform_rad={transform_rad}, combo={combo})"
        ),
    )
    np.testing.assert_allclose(
        result["rad"], extracted_rad, atol=1.0,
        err_msg=(
            f"rad mismatch "
            f"(transform_rad={transform_rad}, combo={combo})"
        ),
    )
