_BASE_: ../deform/deform_base_crop_vessel.yaml
SEED: 2000 # run with 1 gpu

MODEL:
  NAME: "vse_base_cnn_3l_enc_3l_dec_3l_input_edt_lia_fps"
  META_ARCHITECTURE: "PARQ_Deformable_R"
  USE_VESSEL_INFO: "start" # "start", "pos_emb", "no"
  USE_CVS_INFO: "no"
  D_MODEL: 384
  DEFORMABLE:
    DECODER_ONLY: True  # Enable encoder with full self-attention
    USE_VESSEL_MASKED_ENCODER: False  # Use vessel-masked encoder instead of deformable
    WITH_RECURRENCE: False
    SHARED_CENTER_HEAD: True
    USE_GLOBAL_PE: True
    USE_DEFORM_ATTN: False
    N_LEVELS: 3
    LEVEL_SELECTION: "bottom"
    N_ENC_LAYERS: 3  # 1-layer encoder with full self-attention
    N_DEC_LAYERS: 3  # 1-layer decoder
    EFFICIENT_MASK_V2: True
    FIX_PE_SCALE: True
    USE_CHECKPOINT: True
    N_HEADS: 6
    
    FFN_DIM: 512

SOLVER:
  SCANS_PER_BATCH: 8
  SAMPLES_PER_SCAN: 16
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 5.0
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
  SCHED_CYCLE: 48000
  BASE_LR: 0.0001
  MIN_LR: 0.00001
  MAX_ITER: 48000
  FLAT_ITER: 48000
  CHECKPOINT_PERIOD: 2000
TEST:
  PATCHES_PER_ITER: 16 #  24 = ~12GB
  NMS_TOPK: 40
  EVALUATION_CHECKPOINTS: ["0031999", "0035999", "0039999", "0043999", "final"]

DATALOADER:
  NUM_WORKERS: 8
DATA:
  PATCH_SIZE: [64, 64, 64]
  OVERLAP: [32, 32, 32]

  N_CHANNELS: 2 # TODO: automate this parameter so it doesn't require changing when using channels for vessel info
  CROPPING_AUG:
    ROTATION: [90.0, 90.0, 90.0]
    SPACING: [0.9, 1.8]
    PADDED_REORIENT: False
  DIR:
    TRAIN:
      SCAN_DIR: "internal_train/crop_0.4_compressed"
      VESSEL_DIR: "internal_train/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_train/vein_mask_edt_comp"
      ANNOTATION_FILE: "./labels/gt/fp_reviewed/annots/lia_with_fps.csv"


    VAL:
      SCAN_DIR: "internal_test/crop_0.4"
      ANNOTATION_FILE: "./labels/gt/internal_test_crop_0.4.csv"
      VESSEL_DIR: "internal_test/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_test/cvs_mask_edt_comp"
