_BASE_: ../deform/deform_base_crop_vessel.yaml
SEED: 2000

MODEL:
  NAME: "vs_cnn_4l_trx_1l_big_input_edt_lia_fps"
  META_ARCHITECTURE: "PARQ_Deformable_R"
  USE_VESSEL_INFO: "start" # "start", "pos_emb", "no"
  USE_CVS_INFO: "no"
  DEFORMABLE:
    DECODER_ONLY: True
    WITH_RECURRENCE: False
    SHARED_CENTER_HEAD: True
    USE_GLOBAL_PE: True
    USE_DEFORM_ATTN: False
    N_LEVELS: 4
    MASK_NON_VESSEL: True
    EFFICIENT_MASK_V2: True
    FIX_PE_SCALE: True 
    N_DEC_LAYERS: 1
SOLVER:
  SCANS_PER_BATCH: 16
  SAMPLES_PER_SCAN: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 5.0
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
  SCHED_CYCLE: 24000
  BASE_LR: 0.0001
  MIN_LR: 0.00001
  MAX_ITER: 24000
  FLAT_ITER: 24000
  CHECKPOINT_PERIOD: 2000
TEST:
  PATCHES_PER_ITER: 16 #  24 = ~12GB
  NMS_TOPK: 40
  EVALUATION_CHECKPOINTS: ["0007999", "0011999", "0015999", "0019999", "final"]

DATALOADER:
  NUM_WORKERS: 16
DATA:
  PATCH_SIZE: [128, 128, 128]
  OVERLAP: [32, 32, 32]

  N_CHANNELS: 2 # TODO: automate this parameter so it doesn't require changing when using channels for vessel info
  CROPPING_AUG:
    ROTATION: [90.0, 90.0, 90.0]
    SPACING: [0.9, 1.8]
    PADDED_REORIENT: False
  DIR:
    TRAIN:
      SCAN_DIR: "internal_train/crop_0.4"
      VESSEL_DIR: "internal_train/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_train/vein_mask_edt_comp"
      ANNOTATION_FILE: "./labels/gt/fp_reviewed/annots/lia_with_fps.csv"


    VAL:
      SCAN_DIR: "internal_test/crop_0.4"
      ANNOTATION_FILE: "./labels/gt/internal_test_crop_0.4.csv"
      VESSEL_DIR: "internal_test/crop_0.4_vessel_edt_comp"
      CVS_DIR: "internal_test/cvs_mask_edt_comp"
