inf_appends = {
    "decoder_only_no_rec_pe_edt_v2": "final",
    "decoder_only_no_rec_pe_edt_v1": "final",
    "decoder_only_no_rec_input_edt": "50k",
    "decoder_only_no_rec_input_edt_cvs": "52k",
    "postprocess": "50k",
    "one_layer_decoder_only_no_rec_input_edt": "52k",
    "cnn_4l_input_edt": "48k",
    "cnn_4l_input_edt_amp_ogopt": "52k",
    "cnn_4l_input_edt_fp_speedy": "40k",
    #"aug_cnn_4l_short_input_edt_fp_fix": "16k",
    "aug_cnn_4l_short_input_edt": "final",
    "aug_cnn_4l_short":"8k",
    "small_feat_aug_cnn_4l_short_input_edt": "10k",
    "cnn_4l_input_edt_fp_ogopt": "40k",
    #"zaug_cnn_4l_short" :"8k",
    "aug_cnn_4l_short_input_edt_fp_fix": "final",
    "zaug_cnn_4l_short_input_edt": "final",
    "yaug_cnn_4l_short_input_edt": "final",
    "aug_cnn_4l_short_input_edt_fp_strict_fix": "final",
}

thresholds = {
    "decoder_only_no_rec_pe_edt_v2": 0.95,
    "decoder_only_no_rec_pe_edt_v1": 0.95,
    "decoder_only_no_rec_input_edt": 0.96796864,
    "decoder_only_no_rec_input_edt_cvs": 0.8840903,
    "postprocess": 0.84456074,
    "one_layer_decoder_only_no_rec_input_edt": 0.95163065,
    "cnn_4l_input_edt": 0.8951697,
    "cnn_4l_input_edt_amp_ogopt": 0.8,
    "cnn_4l_input_edt_fp_speedy": 0.9,
    "aug_cnn_4l_short_input_edt_fp_fix": 0.93,
    "aug_cnn_4l_short_input_edt": 0.93,
    "aug_cnn_4l_short": 0.9,
    "small_feat_aug_cnn_4l_short_input_edt": 0.93,
    "cnn_4l_input_edt_fp_ogopt": 0.9,
    "zaug_cnn_4l_short": 0.9,
    "zaug_cnn_4l_short_input_edt": 0.93,
    "yaug_cnn_4l_short_input_edt": 0.93,
    "aug_cnn_4l_short_input_edt_fp_strict_fix": 0.93,

}
